package pageObjects;

public interface LoginPageElements
{
String Email="//input[@id='email']";
String Password="//input[@id='password']";
String LoginButton="//span[@class='MuiButton-label']";
String Buttonclick="//img[@alt='btn']";
String designconfigsection="//div[@class='left-bar-menu scroll-styled']//div[@title='Design Configs']";
String addbutton="//span[normalize-space()='Add Page']";
String name="name_input";
String add="//button[@type='submit']";
String addbutton1="//button[@type='submit']//span[@class='MuiButton-label']//*[name()='svg']";
String search="//input[@type='text']";
String tag="//td[@class='MuiTableCell-root MuiTableCell-body'][1]";
String arrow="//button[@type='submit']";
String inputtextdropdown="(//div [@class=' shadow d-flex mx-0 px-0 pt-4 custom-accordion'])[1]//div[@id='text_type_select']";
String inputtext="//textarea[@id='input_text_input']";
String textcomponent="//div [@class='MuiAccordionSummary-content' and contains(.,Basic Components)]";
String Carousalscontent="//div[contains(text(),'Carousels')]";
String CarousalcomonentH2title="//*[@id=\"root\"]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div/div/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div/div[2]/div/input";
String CarousalcomonentH3title="//*[@id=\"root\"]/div[2]/div/div[2]/div[2]/div/div/div[2]/div/div[1]/div/div/div/div[2]/div/div[1]/div/div[2]/div[2]/div/div/div[7]/div[2]/div[2]/div[1]/div/input";
String ImageComponents="//div[contains(text(),'Image Components')]";
String Imagebutton="//input[@type='file']";
String paddingbtntop="//input[@id='padding_top_input']";
String paddingbtnbottem="//input[@id='padding_bottom_input']";
String H1dropdown="(//div [@class=' shadow d-flex mx-0 px-0 pt-4 custom-accordion'])[1]//div[@id='text_type_select']";
String Visibletext="//li[text()='H3- Body']";
String Comonentcolapse="//div[@class=' component-title col-md-10 ps-2'][normalize-space()='Text']";
String Hotelmoduledropdown="//div[@id='hotel_module_select']";
String Visibletext1="//li[text()='Hotel Compendium']";
String selectredirect="//input[@value='view_all_status_inactive']";
String Visibletext2="//li[text()='test26']";
String slid2="//span[normalize-space()='Slide 2']";
String slidremove2="//div[contains(@class,'text-underlined pointer')]";
String slid3="//span[normalize-space()='Slide 3']";
String slide3remove="//div[contains(@class,'text-underlined pointer')]";
String slid4="//span[normalize-space()='Slide 4']";
String slide4remove="//div[contains(@class,'text-underlined pointer')]";
String hotelcomadium="(//div[@class='MuiFormControl-root w-100'])[2]";
String visibletext3="//li[text()='Conventions']";
String colapse="//div[@class=' component-title col-md-10 ps-2'][normalize-space()='6 - Large IMG w/Carousel']";
String Saveasdraft="//span[text()='Save as Draft']";
String collapse3="//div[contains(@class,'component-title col-md-10 ps-2')][normalize-space()='15 - Large Image']";
String Hotelmoduledropdown1="//div[normalize-space()='Restaurant']//div[@id='hotel_module_select']";
String Restaurant="(//div[@class='MuiSelect-root MuiSelect-select MuiSelect-selectMenu MuiInputBase-input MuiInput-input' and @id='hotel_module_select'])[2]";
String Visibletext6="//li[text()='Restaurant']";
String visibletext7="//li[text()='english']";
String collapse4="//div[contains(@class,'component-title col-md-10 ps-2')][normalize-space()='Text']";
String collapse5="//div[@class=' component-title col-md-10 ps-2'][normalize-space()='6 - Large IMG w/Carousel']";
String collapse6="//div[@class=' component-title col-md-10 ps-2'][normalize-space()='15 - Large Image']";
String Save="//span[text()='Save as Draft']";
String drag1="//div[@id='basicComponentcontent']//div[contains(@class,'align-items-center justify-content-center')]";
String target1="//div[contains(@class,'d-flex align-items-center justify-content-center h-100')]";
String drag2="//div[contains(text(),'6 - Large IMG w/Carousel')]";
String target2="//div[@class='droppable page-builder-space']";
String drag3="//div[contains(text(),'15 - Large Image')]";
String target3="//div[@class='page-builder-scroll scroll-styled']";
String uploadelement1="//div[@class='mb-4 mt-4']//div[@class='d-flex align-items-center img-select justify-content-center']";
String uploadelement2="(//div[@class='d-flex align-items-center img-select justify-content-center'])[2]";
String uploadelement3="(//div[contains(@class,'d-flex align-items-center img-select justify-content-center')])[1]";
String click="//div[@class='col-md-9']";
String cancelbutton="//*[name()='path' and contains(@d,'M12 2C6.47')]";
}
